spring.application.name=relation

spring.datasource.url=jdbc:mysql://localhost:3306/relationdb
spring.datasource.username=root
spring.datasource.password=!Q@W3e4r
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# sql 보이기
spring.jpa.show-sql=true
# sql 개행 추가
spring.jpa.properties.hibernate.format_sql=true
# sql 색상 추가
spring.jpa.properties.hibernate.highlight_sql=true

spring.jpa.hibernate.ddl-auto=update


spring.web.resources.add-mappings=false