### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### create user
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "username": "ttt4",
  "email": "4@123.com",
  "nickname": "ttt4",
  "age": 28
}

### Get All User
GET http://localhost:8080/v1/users
Content-Type: application/json

### Get One User
GET http://localhost:8080/v1/users/3
Content-Type: application/json

### update One user
PUT http://localhost:8080/v1/users/3
Content-Type: application/json

{
  "email": "120@123.com",
  "nickname": "ttttt5555",
  "age": 22
}

### Delete One User
DELETE http://localhost:8080/v1/users/3
Content-Type: application/json


### Get One User
GET http://localhost:8080/v1/users/search?value=27
Content-Type: application/json