### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### create user
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "username": "tttt0",
  "email": "120@123.com",
  "nickname": "ttttt0",
  "age": 26
}

### Get All User
GET http://localhost:8080/v1/users
Content-Type: application/json

### Get One User
GET http://localhost:8080/v1/users/3
Content-Type: application/json

### update One user
PUT http://localhost:8080/v1/users/3
Content-Type: application/json

{
  "email": "120@123.com",
  "nickname": "ttttt5555",
  "age": 22
}
