### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### create One
@postId =1
POST http://localhost:8080/posts/{{postId}}/comments
Content-Type: application/json

{
  "content": "new content"
}