### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Create One
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "new title 3",
  "content": "new content 3",
  "author": "author 3"
}

### 특정 Post Tag 추가 중요
POST http://localhost:8080/posts/1/tags
Content-Type: application/json

{
  "name": "java"
}

### 단건 : create Post + List<Tag> 비즈니스로직 개념
POST http://localhost:8080/posts/tags
Content-Type: application/json

{
  "title": "널 지켜 줄거라고 믿고 있어",
  "content": "누구라도 얕보다간 큰일나",
  "author": "ji-woo",
  "tags" : ["java", "spring", "react", "special", "limit"]
}

### find All
GET http://localhost:8080/posts
Content-Type: application/json

### find All + Tag
GET http://localhost:8080/posts/tags?tagName=java
Content-Type: application/json


### find One V1
GET http://localhost:8080/posts/1
Content-Type: application/json

### find One V2
GET http://localhost:8080/posts/v2/1
Content-Type: application/json

### find One With Count Comment
GET http://localhost:8080/posts/1/count-comment
Content-Type: application/json

### Find All With Count Comment
GET http://localhost:8080/posts/count-comment
Content-Type: application/json

### Find One With Comment Count + DTO 중요
GET http://localhost:8080/posts/count-comment-dto
Content-Type: application/json

### Find One With Comment Count + Tags 중요
GET http://localhost:8080/posts/1/detail
Content-Type: application/json

### Find One With Comment Count + Tags V2 중요
GET http://localhost:8080/posts/64/detail/v2
Content-Type: application/json

### Find All With Comment Count + Tags 중요
GET http://localhost:8080/posts/detail
Content-Type: application/json

### Update One
PUT http://localhost:8080/posts/2
Content-Type: application/json

{
  "title": "Update title",
  "content": "Update content",
  "author": "author"
}

### Delete One
DELETE http://localhost:8080/posts/42
Content-Type: application/json


/////////////////// Pagination

### find all
GET http://localhost:8080/posts/pages-detail?page=3
Content-Type: application/json

### find all v2
GET http://localhost:8080/posts/pages-detail-v2?page=5&size=5
Content-Type: application/json


/////////////// process image

### 단건 이미지 처리
POST http://localhost:8080/posts/images
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="러닝메이트.jpg"

< C:/Users/Lee/Documents/카카오톡 받은 파일/KakaoTalk_20241113_091504668_04.jpg

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "title": "new title 3",
  "content": "new content 3",
  "author": "author 3"
}
--WebAppBoundary--