### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Create
POST http://localhost:8080/tags
Content-Type: application/json

{
  "name" : "javascript"
}

### Find All
GET http://localhost:8080/tags
Content-Type: application/json
